### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by musasabi23** [musasabi23/furima-39920#23]
# URL
https://furima-39920.onrender.com/

# Basic認証のIDとパスワード
ID  admin
パスワード  5555

# 出品者用のメールアドレスとパスワード
test@test.com
111qqq

# 購入者用のメールアドレスとパスワード
sample@sample.com
222www

**Comment by mo1015** [comment]
@musasabi23 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
一度出品に失敗しエラーが出た後に再度価格を入力すると、販売手数料と販売利益が表示されなくなってしまいます。どの段階でも入力したら表示されるよう修正しましょう。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by musasabi23** [comment]
ご確認していただきありがとうございます。
「一度出品に失敗しエラーが出た後に再度価格を入力すると、販売手数料と販売利益が表示されなくなってしまう」とのご指摘でしたが、確認したところ正常に動作しておりました。
再確認をお願いいたします。
・動画：https://gyazo.com/c638c7b394e9b43341554fa05247a2b2

**Comment by mo1015** [comment]
@musasabi23 さん、再度ご提出ありがとうございます。
大変申し訳ございません。修正箇所のご案内に誤りがございました。
お手数をおかけしてしまい恐縮ですが、以下の内容で再度ご対応いただけますと幸いです。

[修正依頼箇所]

- [ ] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
計算が合わず、販売利益が正しい金額で表示されておりません。画像の例ですと、2700円と表示されるよう修正をお願いします。
<img width="628" alt="スクリーンショット 2024-02-26 11 48 10" src="https://github.com/musasabi23/furima-39920/assets/62644781/85762046-3c0f-4422-805f-e6b967b8416f">


修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by musasabi23** [comment]
計算式を修正いたしました。
ご確認をお願いいたします。

**Comment by mo1015** [comment]
@musasabi23 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
